### ISSUE TITLE
Support for older versions/custom Jars?

### ISSUE THREAD

**Issue by schoolgaminghd** [vantezzen/cauldron-js#17]
This would be cool, because there is a project called ayuncraft https://github.com/ayunami2000/ayuncraft that lets you play minecraft in your web browser, but its 1.5.2, i was wondering if you could add support for 1.5.2.
(NOTE: I linked a fork that would be possible to use on, servers for the original version need another program running, and not just the server software, it would be stupid to add support for extra programs)

**Comment by mtnskye** [comment]
how do i use ur single player

**Comment by vantezzen** [comment]
CauldronJS currently is an experimental, complete rewrite of the Minecraft server from scratch and doesn't use any Minecraft Server JARs.
I thought about compiling some Minecraft Server project (original or some fork) to WebAssembly for this, but that would require a complete rewrite of the project, which isn't currently planned.
